# Generated by Django 4.1.2 on 2022-10-16 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Meeting Description', max_length=255)),
                ('document', models.FileField(upload_to='uploads/documents/s/%Y/%m/%d')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published Date')),
                ('status', models.CharField(blank=True, choices=[('SPECIAL', 'Special'), ('REGULAR', 'Regular')], max_length=20, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'ordering': ['-publish'],
            },
        ),
    ]
